---
title: "sample summary"
author: "baf44"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(devtools)
library(padr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(tidyr)

load_all("/Users/baf44/projects/dataREACHr")

# set base_dir
base_dir = "/Users/baf44/Library/CloudStorage/OneDrive-ThePennsylvaniaStateUniversity/b-childfoodlab_Shared/Active_Studies/MarketingResilienceRO1_8242020/ParticipantData/"

# define names of redcap files to process
visit_file_name =  "FoodMarketingResilie_DATA_2024-08-14_1522.csv"
double_entry_file_name = "REACHDataDoubleEntry_DATA_2024-08-14_1521.csv"

#### process redcap data ####

# assign paths to data downloaded from redcap
visit_data_path = paste0(base_dir, "/bids/sourcedata/phenotype/", visit_file_name)
data_de_path = paste0(base_dir, "/bids/sourcedata/phenotype/", double_entry_file_name)

# process redcap data
redcap_data <-
  proc_redcap(visit_data_path,
              data_de_path,
              overwrite = FALSE,
              return_data = TRUE)

# process task data
task_data <-
  proc_task(
    base_wd = base_dir,
    overwrite_sourcedata = FALSE,
    overwrite_rawdata = FALSE,
    overwrite_jsons = FALSE,
    return_data = TRUE
  )

#extract participants data
participants_data <- redcap_data$phenotype_data$participants

# make lists of high-risk and low-risk subject IDs
high_risk_subs <- participants_data[participants_data$risk_status_maternal == "high-risk", "participant_id"]
low_risk_subs <- participants_data[participants_data$risk_status_maternal == "low-risk", "participant_id"]

```


```{r data collection over time plot}

dates_long <- participants_data %>% 
  pivot_longer(
    cols = c("child_protocol_1_date", "child_protocol_2_date", "child_protocol_3_date", "child_protocol_4_date", "child_protocol_5_date"), 
    names_to = "visit",
    values_to = "date"
)

# get start and latest dates
start_date <- min(dates_long$date, na.rm = TRUE)
latest_date <- max(dates_long$date, na.rm = TRUE)

# define function to get cumulative count of visits by date
cumulative_visit_counter <- function(data, var) {
  # data is name of dataframe
  # var is character vector of column name

  count_data <- data %>% count(.data[[var]], name = "counts") %>%
  filter(!is.na(.data[[var]])) %>% pad(
    start_val = min(dates_long$date, na.rm = TRUE),
    end_val = max(dates_long$date, na.rm = TRUE),
    interval = "day"
  ) %>% fill_by_value(counts, value = 0) %>%
  mutate(cumulative_count = cumsum(counts)) %>%
  rename_with(~paste0(var, "_cumcount"), cumulative_count) %>%
  select(-counts)
  
  return(count_data)
}

# Create a sequence of dates between the start and end dates
date_sequence <- data.frame(date = seq.Date(from = start_date, to = latest_date, by = "day"))

# apply function for each variable and add data to date_sequence
for (var in c("child_protocol_1_date", "child_protocol_2_date", "child_protocol_3_date", "child_protocol_4_date", "child_protocol_5_date") ) {

  counts <- cumulative_visit_counter(participants_data, var)

  date_sequence <- date_sequence %>%
    left_join(counts, by = c("date" = var))
}

cumulative_long <- date_sequence %>% 
  pivot_longer(
    cols = c("child_protocol_1_date_cumcount", "child_protocol_2_date_cumcount", "child_protocol_3_date_cumcount", "child_protocol_4_date_cumcount", "child_protocol_5_date_cumcount"), 
    names_to = "visit",
    values_to = "count"
)

# plot cumulative count over time by visit
ggplot(cumulative_long, aes(x = date, y = count)) + 
  geom_line(aes(color = visit), size = 1) +
  theme_minimal()

```

To do: figure out which children have BMI's outside of range

# Visits by risk

```{r visit counts by risk counts}

# make long dataframe of visit dates
visits_long <- participants_data %>%
  pivot_longer(cols = child_protocol_1_date:child_protocol_5_date, names_to = "child_protocol_number", values_to = "child_protocol_date") %>%
  filter(!is.na(child_protocol_date))


# Plot: visit protocol counts by risk status
ggplot(visits_long, aes(x = child_protocol_number, fill = risk_status_maternal.y)) +
  geom_bar(position = "dodge", stat = "count") +
  geom_text(data = counts, aes(x = Column, y = Count, label = Count, group = risk_status_maternal.y),
            position = position_dodge(width = 0.9), vjust = -0.5) +
  labs(title = "Number of Visits per Visit Protocol by Risk", x = "Visit protocol", y = "Count") +
  theme_minimal()


```

# Task data by risk 

```{r PIT }

# baseline and followup
ses1_pit_subs <- names(task_data$pit_data[['ses-1']])
ses2_pit_subs <- names(task_data$pit_data[['ses-2']])

intersect(ses1_pit_subs,ses2_pit_subs) # list subs in ses-1 and ses-2
setdiff(ses1_pit_subs, ses2_pit_subs) # list subs in ses-1 but not ses-2
setdiff(ses2_pit_subs, ses1_pit_subs) # list subs in ses-2 but not ses-1


```

```{r Space Game }

# baseline only 

```

```{r NIH toolbox }

# baseline and followup
ses1_toolbox_subs <- names(task_data$toolbox_data[['ses-1']])
ses2_toolbox_subs <- names(task_data$toolbox_data[['ses-2']])

intersect(ses1_toolbox_subs,ses2_toolbox_subs) # list subs in ses-1 and ses-2
setdiff(ses1_toolbox_subs, ses2_toolbox_subs) # list subs in ses-1 but not ses-2
setdiff(ses2_toolbox_subs, ses1_toolbox_subs) # list subs in ses-2 but not ses-1

```

```{r RRV }
# rrv is at baseline only

rrv_subs <- names(task_data$rrv_data)

# count by risk group
length(intersect(ses1_rrv_subs,high_risk_subs))
length(intersect(ses1_rrv_subs,low_risk_subs))

```
