---
title: ""
author: "baf44"
date: ""
output: html_document
editor_options: 
  chunk_output_type: console
---

## Set up

```{r load file}
library(dplyr)
library(ggplot2)
```

```{r load data }

# load behavioral files generated by /ParticipantData/bids/code/beh_into_bids.R (run locally)

beh_byrun <- read.delim("~/Library/CloudStorage/OneDrive-ThePennsylvaniaStateUniversity/b-childfoodlab_Shared/Active_Studies/MarketingResilienceRO1_8242020/ParticipantData/bids/derivatives/beh_summary_databases/sst_long_by_run.tsv", na.strings = "n/a")
```

# Data processing

Data was processed by dataREACHr functions util_task_sst.R (called by proc_task.R) and deriv_sst.R. The following cleaning steps occurred:

1.  

2.  

3.  

# Histograms - task completion
```{r run completion}

fmri_beh <- beh_byrun[beh_byrun$type == "fMRI",]

# count number of children with N runs completed
run_count_by_sub <- fmri_beh %>% group_by(sub) %>% summarise(
  n_complete = n(),
  n_pass = sum(racehorse_check==1)
) 

long_table_A <- run_count_by_sub %>% group_by(n_complete) %>% 
  summarise(
    n_subs = n(),
    metric = "completed"
  ) %>% rename('n_runs' = 'n_complete')

long_table_B <- run_count_by_sub %>% group_by(n_pass) %>% 
  summarise(
    n_subs = n(),
    metric = "passed assumption"
  ) %>% rename('n_runs' = 'n_pass')

# grouped barplot 
ggplot(rbind(long_table_A, long_table_B), aes(fill=metric, y=n_subs, x=n_runs)) + 
    geom_bar(position="dodge", stat="identity") +
    ggtitle("Stop Signal Task fMRI task status") +
    xlab("Number of runs") +
    ylab("Number of children") + 
    scale_fill_discrete(name = "Run status") +
    scale_x_continuous(breaks=c(seq(1:6))) +
    theme_bw() + 
    theme(plot.title = element_text(hjust = 0.5))

```

# Histograms - performance metrics

Histograms are produced for metrics derived by run of the Stop Signal Task.

## Metric 1

```{r }


```