---
title: ""
author: "baf44"
date: ""
output: html_document
editor_options: 
  chunk_output_type: console
---

## Set up

```{r load file }
library(dplyr)

# load file generated by ParticipantData/bids/derivatives/analyses/sst/level_2/gen_group_censor_summary.py (run on Roar Collab)
group_censor_summary <- read.delim("~/Library/CloudStorage/OneDrive-ThePennsylvaniaStateUniversity/b-childfoodlab_Shared/Active_Studies/MarketingResilienceRO1_8242020/ParticipantData/bids/derivatives/analyses/sst/level_2/group_censor_summary.tsv")

```

```{r count runs , include=FALSE}

run_count <- group_censor_summary %>% group_by(sub)  %>% summarise(
  total_runs = n(),
  runs_p_all_.8 = sum(p_uncensored_trs > .8),
  runs_p_all_.7 = sum(p_uncensored_trs > .7),
  runs_p_all_.6 = sum(p_uncensored_trs > .6),
  runs_p_all_.5 = sum(p_uncensored_trs > .5)
)

hist(run_count$runs_p_all_.5)
hist(run_count$runs_p_all_.6)
hist(run_count$runs_p_all_.7)
hist(run_count$runs_p_all_.8)

# combine this data with beh to see runs that have "good" motion + pass racehorse assumption 
```
