---
title: ""
author: "baf44"
date: ""
output: html_document
editor_options: 
  chunk_output_type: console
---

## Set up

```{r load file }
library(dplyr)

# load file generated by ParticipantData/bids/derivatives/analyses/foodview/level_2/gen_group_censor_summary.py (run on Roar Collab)
group_censor_summary <- read.delim("ParticipantData/bids/derivatives/analyses/foodview/level_2/group_censor_summary.tsv")
```

```{r count runs , include=FALSE}

run_count <- group_censor_summary %>% group_by(sub)  %>% summarise(
  total_runs = n(),
  runs_p_image_.8 = sum(p_uncensored_image_trs > .8),
  runs_p_image_.5 = sum(p_uncensored_image_trs > .5),
  runs_p_all_.8 = sum(p_uncensored_trs > .8),
  runs_p_all_.5 = sum(p_uncensored_trs > .5),
  runs_p_comm_.8 = sum(p_uncensored_commerical_trs > .8),
  runs_p_comm_.5 = sum(p_uncensored_commerical_trs > .5),
  runs_p_image_comm_.5 = sum(p_uncensored_commerical_trs > .5 & p_uncensored_image_trs > .5),
  runs_p_image_comm_.7 = sum(p_uncensored_commerical_trs > .7 & p_uncensored_image_trs > .7)
)
```
